### ISSUE TITLE
Info/Erro to install

### ISSUE THREAD

**Issue by Kathou99** [Jerrie-Aries/modmail-plugins#1]
Hi, I try to download and install your pluging to my modmail but I got this error:

```py
Failed to download plugin, check logs for error.
<class 'OSError'>: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\[BOTS]\modmail2022\temp\plugins-cache\https:-\github.com-master.zip'
```

The command was

```
?plugin install  https://github.com/Jerrie-Aries/modmail-plugins/wiki/Log-Viewer-plugin
```

And samething with 

```
?plugin install Jerrie-Aries/modmail-plugins/logviewer@development
```

Thank :)

**Comment by Jerrie-Aries** [comment]
> ?plugin install https://github.com/Jerrie-Aries/modmail-plugins/wiki/Log-Viewer-plugin

That command is wrong. That's the link to the wiki.

> Failed to download plugin, check logs for error.
<class 'OSError'>: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:[BOTS]\modmail2022\temp\plugins-cache\https:-\github.com-master.zip'

This error was raised because you use the invalid/wiki link above to install the plugin.

Are you hosting your bot on your local computer? If so, it's not supported. Your host must be able to run a web server (has domain, etc) to use this plugin.

**Comment by Kathou99** [comment]
Local computer no, a server yesAnd okay

**Comment by Jerrie-Aries** [comment]
Sorry for the inconvenience. I only tested this on Replit, Railway and Heroku. And only two of the former ones work, the latter does not work.

May I know what VPS you are using?

**Comment by Kathou99** [comment]
Hi, it is a server with a window VM running window server 2019

**Comment by Jerrie-Aries** [comment]
> Hi, it is a server with a window VM running window

Not sure if that would work. As of now, I only tested it on *Replit* and *Railway*.
Local computers and VPS's would work too I assume but only for testing locally and cannot be accessed from outside. Unless you know what you're doing with the `IP`/`HOST` thing, you can set that in the environment config variables (`.env`).

**Comment by ririko5834** [comment]
I have same problem

?plugin install Jerrie-Aries/modmail-plugins/logviewer

Failed to download plugin, check logs for error.
<class 'cogs.plugins.InvalidPluginError'>: Cannot load extension, plugin invalid.

**Comment by ririko5834** [comment]
```12/09/22 14:12:30 plugins.Jerrie-Aries.modmail-plugins.logviewer-master.core.servers[99] - INFO: Starting log viewer server.
12/09/22 14:12:31 cogs.plugins[264] - ERROR: Plugin load failure: plugins.Jerrie-Aries.modmail-plugins.logviewer-master.logviewer
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 946, in _load_from_module_spec
    await setup(self)
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/logviewer.py", line 125, in setup
    await bot.add_cog(Logviewer(bot))
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 782, in add_cog
    cog = await cog._inject(self, override=override, guild=guild, guilds=guilds)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 644, in _inject
    await maybe_coroutine(self.cog_load)
  File "/home/container/.local/lib/python3.9/site-packages/discord/utils.py", line 650, in maybe_coroutine
    return await value
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/logviewer.py", line 45, in cog_load
    await self.server.start()
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/core/servers.py", line 107, in start
    await asset.save(favicon_path)
  File "/home/container/.local/lib/python3.9/site-packages/discord/asset.py", line 119, in save
    data = await self.read()
  File "/home/container/.local/lib/python3.9/site-packages/discord/asset.py", line 87, in read
    return await self._state.http.get_from_cdn(self.url)
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 768, in get_from_cdn
    raise NotFound(resp, 'asset not found')
discord.errors.NotFound: 404 Forbidden (error code: 0): asset not found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/cogs/plugins.py", line 259, in load_plugin
    await self.bot.load_extension(plugin.ext_string)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 951, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'plugins.Jerrie-Aries.modmail-plugins.logviewer-master.logviewer' raised an error: NotFound: 404 Forbidden (error code: 0): asset not found
12/09/22 14:12:31 cogs.plugins[159] - ERROR: Error when loading plugin Jerrie-Aries/modmail-plugins/logviewer@master. Plugin removed from config.
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 946, in _load_from_module_spec
    await setup(self)
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/logviewer.py", line 125, in setup
    await bot.add_cog(Logviewer(bot))
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 782, in add_cog
    cog = await cog._inject(self, override=override, guild=guild, guilds=guilds)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 644, in _inject
    await maybe_coroutine(self.cog_load)
  File "/home/container/.local/lib/python3.9/site-packages/discord/utils.py", line 650, in maybe_coroutine
    return await value
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/logviewer.py", line 45, in cog_load
    await self.server.start()
  File "/home/container/plugins/Jerrie-Aries/modmail-plugins/logviewer-master/core/servers.py", line 107, in start
    await asset.save(favicon_path)
  File "/home/container/.local/lib/python3.9/site-packages/discord/asset.py", line 119, in save
    data = await self.read()
  File "/home/container/.local/lib/python3.9/site-packages/discord/asset.py", line 87, in read
    return await self._state.http.get_from_cdn(self.url)
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 768, in get_from_cdn
    raise NotFound(resp, 'asset not found')
discord.errors.NotFound: 404 Forbidden (error code: 0): asset not found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/cogs/plugins.py", line 259, in load_plugin
    await self.bot.load_extension(plugin.ext_string)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 951, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'plugins.Jerrie-Aries.modmail-plugins.logviewer-master.logviewer' raised an error: NotFound: 404 Forbidden (error code: 0): asset not found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/cogs/plugins.py", line 156, in initial_load_plugins
    await self.load_plugin(plugin)
  File "/home/container/cogs/plugins.py", line 265, in load_plugin
    raise InvalidPluginError("Cannot load extension, plugin invalid.") from exc
cogs.plugins.InvalidPluginError: Cannot load extension, plugin invalid.```

**Comment by ririko5834** [comment]
Running it on Linux vps with Debian OS

**Comment by Jerrie-Aries** [comment]
Hello there. Looking at the error, it seems like it failed to download your bot's avatar. Do you have it set?

**Comment by ririko5834** [comment]
Nope

**Comment by Jerrie-Aries** [comment]
> Nope

Set the bot's avatar, and try reinstalling the plugin.

**Comment by ririko5834** [comment]
Can you fix it so it works with no avatar too?

**Comment by ririko5834** [comment]
It works but it should work also without avatar

**Comment by Jerrie-Aries** [comment]
> Can you fix it so it works with no avatar too?
> 

I'll look into it.
